### ISSUE TITLE
Problem with cursor on 200% scaling

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#100]
In preliminary tests I also had problems with cursor position. But this might be due to running on a 4k notebook display on 200% scaling which essentially scales the SDL scaled image again. I need to look into this again.

Oh yes. If you up scale more than 100% (in Windows) It breaks the cursor
alignment. It has been like that for along time. I did occure to me this
would be a problem for 4k where it is normal to increase zoom. But I never
logged it. My bad

Ah, good to know. At home I usually run this on a second 1440p screen with 100% scaling and I had no problems at all.

If you were fixing mouse behavior in scaled resolutions, it would be a good idea to put the code in port_vga_mouse.cpp, not in the game code.

**Comment by thobbsinteractive** [comment]
We can leave this for another day. It is not that urgent

**Comment by thobbsinteractive** [comment]
So there seems to be a fix for this:
https://stackoverflow.com/questions/59829969/why-is-my-vs-sdl-2-0-window-2x-bigger-than-i-specified
At least under Windows. I have tested it and it works
