### ISSUE TITLE
targeting fire balls is off

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#101]
So the targeting is off. The fire balls fly right at their target, but only occasionally impact.
Turican:I have not registered this error, I will look into it further.

**Comment by thobbsinteractive** [comment]
Thanks for logging this Tom. I would like to get this fixed before the pull request is merged to development.

**Comment by turican0** [comment]
I did not notice this error

**Comment by thobbsinteractive** [comment]
They target correctly, but they either pass the target or terminate without hitting the target and doing damaging.

**Comment by thobbsinteractive** [comment]
We have definitely had this problem before a long time ago. In the first level it should only take a few shots to kill an archer or a goat.

**Comment by turican0** [comment]
Now I tried it and in DOSBOX and our version I find killing the archer equally easy - 5 shots.

**Comment by turican0** [comment]
My mistake I accidentally tried it in an older revision, it doesn't really work in the current one.

**Comment by turican0** [comment]
Test:
246b30 - CastPlayerFire_65B30(a1_6E8E);//fly fire projectile
200f40 - AddArcher0504_1FF40(a1_6E8E);
2504a0 - AddSwitch0B_11_6F4A0(a1_6E8E);(get scroll)
2501c0 - AddSwitch0B_20_6F1C0(a1_6E8E);
24aab0 - sub_69AB0(a1_6E8E);//0x0f 0x02 pos 0xc2 0xd5(get scroll)
245e20 - AddTree02_00_64E20(a1_6E8E);
201010 - HitArcher_20010(a1_6E8E);
201040 - KillArcher_20040(a1_6E8E);
216940 - TransformArcherToMana_35940(a1_6E8E);
2482e0 - AddArcherArrow_672E0(a1_6E8E);

**Comment by turican0** [comment]
Now I tried it several times and I always killed the archers for 5 shots, I hope the bug is solved. Please try it too.

**Comment by turican0** [comment]
Ideally, if you test with #define PLAYING_GAME(game with autosave)
and if you find an error, send me the saves folder.
That way I can then easily find the bottleneck.

**Comment by thobbsinteractive** [comment]
Yep it is fixed

**Comment by 3456523** [comment]
Hi201010
