### ISSUE TITLE
pause menu text does not show in full HD

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#102]
Also the pause menu text does not show in full HD, but this might be an existing scaling issue, but I believe I have seen this before and I thought I had fixed it

**Comment by thobbsinteractive** [comment]
I am not as sure about this one. Like you said in the comment, I think it is an older issue

**Comment by turican0** [comment]
I did not notice this error

**Comment by thobbsinteractive** [comment]
Yeah this seems to be working in the latest version of your PR.
