### ISSUE TITLE
Something is wrong with the terrain

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#103]
Something is wrong with the terrain. These screen shots were taken from the GOG version and this branch on Level 5
![image](https://user-images.githubusercontent.com/19335188/178576552-bf0dbff8-6269-414a-b282-65ab89581fc6.png)

**Comment by turican0** [comment]
It's OK in my earlier revision. So it will be enough to compare with it and I don't have to compare it with the DOSBOX version. I'm guessing it's a signed/unsigned issue, or something similar. I'll try to fix it tomorrow.

**Comment by thobbsinteractive** [comment]
Cool thanks man

**Comment by turican0** [comment]
I compare x_BYTE_11B4E0_heightmap in point 00224959

**Comment by thobbsinteractive** [comment]
It almost looks like there is less terrain than there should be. It is not just the height. Notice in the screen shot the crater in the top of the hill is deeper but also not as wide. I test this level often, so it is definitely a bug in the PR somewhere

**Comment by turican0** [comment]
It doesn't really matter what's wrong with the terrain. I'm comparing the data to the original, so the result must be a workable terrain.

**Comment by turican0** [comment]
fixed
