### ISSUE TITLE
Videos and level selection are playing too slow

### ISSUE THREAD

**Issue by GrimSqueaker** [thobbsinteractive/magic-carpet-2-hd#115]
I noticed that on the Raspberry Pi the video was playing very smoothly. On my notebook, however, the video and level selection screen feel like 5-10 fps. This was not the case for @turican0's branch before there merge - only on @thobbsinteractive's branch. And now it persists after the merge.
Do you have any idea what might cause this or where I could start looking into frame rate regulation for video and level selection screen?

**Comment by thobbsinteractive** [comment]
Maybe it is the locking for the Sub_Blit that was introduced in the last merge?

**Comment by GrimSqueaker** [comment]
Nope, tested it. Same behaviour. It must be an older change. From before the big merge between the two repos. Do you know what is controlling the framerate in the main menu / level selection?

**Comment by thobbsinteractive** [comment]
No. Honestly I did not think they needed controlling, but thinking about they must. But there is a limit after the VGA_Blit that measures the previous frame and delays using the remaining time and the setting in 'speed'. I am not sure it has been working of late as in the 320x200 game render we hit 130 FPS.

**Comment by GrimSqueaker** [comment]
So, if I play with `mydelay` in `port_time.cpp`, I can speed it up. But that hasn't changed in years. I'll investigate a bit.

**Comment by GrimSqueaker** [comment]
I think I found the reason but not a way to fix it yet. It again boils down to `clock()` not returning wall-clock time on linux. This is similar to the problem we had with the fps counter. I'll check if I can replace the `clock()` calls in `port_time.cpp` and maybe other places, too.

**Comment by GrimSqueaker** [comment]
So, I have fixed the speed of videos and the level selection in Linux [with this commit](https://github.com/GrimSqueaker/remc2/commit/eacff094cef748ae74b964cf7375d82422cb1061).
However, now the fires in the main menu are not animated anymore.
It seems like we have contradicting uses of the time points returned from `port_time.cpp`.

**Comment by turican0** [comment]
Speed errors should be eliminated, but this does not mean that it is desirable to increase speed everywhere. Subtitles may not be readable at higher video speeds. When selecting a level, the dragons fly again. It's an old game where actions are tied to framerate, so we can only affect it to a certain extent.

**Comment by GrimSqueaker** [comment]
Agreed. But in this case `clock()` is just not correct on Linux as it measures CPU time instead of wall clock time. This means that  the game runs too slow by a factor of 10, because it just uses 10% CPU during the main menu and videos.
