### ISSUE TITLE
GameRenderHD - bad help position for spell icons

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#128]
![image](https://user-images.githubusercontent.com/41465132/183713708-8eb309d3-f3db-4df4-96c9-bfbf7ce69fc9.png)

**Comment by thobbsinteractive** [comment]
Yeah I know about this one. Thanks for logging in

**Comment by turican0** [comment]
You may want to adjust the positions of the two spell icon entries in the str_E2A74 structure when changing the resolution.

**Comment by turican0** [comment]
I see to it,
help text get in void sub_87610()//268610
str_unk_1804B0ar is set from &str_E2A74[10].axis_2[1]
may be add to this cycle:
for (i = 0; i < a2; str_unk_1804B0ar.uni_0x8a.word[i + 1] = a3x[i - 1])//*(int16_t*)(a3 + 2 * i - 2))
  i++;
some this:
if(not defaulres)
{
str_E2A74[10].axis_2[1]+=screenwidth-640;
str_E2A74[10].axis_2[3]+=screenwidth-640;
}

But I can't quite find it exactly, I'll look at it tomorrow, there's a lot of features we can clean up.

**Comment by thobbsinteractive** [comment]
It should be easy for this particular issue as only those two icons are shifted across the screen. 
The Spell menu is more of an issue if context help displays for that. The pause menu is the same height by like the spell menu shifted across the screen.

**Comment by turican0** [comment]
So far I've fixed it like this:

		str_unk_1804B0ar.dword_0x76 = 0;
		str_unk_1804B0ar.byte_0xa0 = a2;
		for (i = 0; i < a2; str_unk_1804B0ar.uni_0x8a.word[i + 1] = a3x[i])
			i++;

		if (!DefaultResolutions())
		{
			if (str_E2A74[10].axis_2[1] == a3x[1])
			{
				a3x[3] += screenWidth_18062C - 640;
			}
		}
For the pause menu, I get the hint displayed fine. If not for you, post a screenshot.

I would like to fix the range where help can be displayed, but that is not necessary.

When you finish your pull request, I'll start posting those fixes. Mainly I cleaned up some procedures and named variables.

**Comment by thobbsinteractive** [comment]
Ideally to make it more flexible/modular we could pass in the width and height to the method. But the fix looks good. The merge is done.

**Comment by turican0** [comment]
When you want to go into VR write me, I'll try to fix the code as much as possible. There's a piece of code JUMPOUT(__CS__, *(&off_75628 + (unsigned __int8)byte_17D441[dword_17D698])); that didn't decompile, so I'd try to decompile it manually, maybe there'll be something interesting.

**Comment by turican0** [comment]
I've tried Stereogram in MC1, but I find it useless - it's unplayable. But there is a setting for blue-red glasses, that's more meaningful.

**Comment by thobbsinteractive** [comment]
@turican0. I implemented the change you asked for (hopefully correctly in Dev) Can we close this?

**Comment by turican0** [comment]
Sure we can close, thanks.
