### ISSUE TITLE
After some update can not build Windows 64bit solution

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#133]
![image](https://user-images.githubusercontent.com/41465132/184388848-6d0f8027-9ac5-4b8c-a56a-ad8ccd3e4e19.png)
It will probably be enough to override the variables (char*).

**Comment by turican0** [comment]
It might be worth putting Win64 into Github actions.

**Comment by thobbsinteractive** [comment]
Yep. Maybe.
I honestly don't think we will ever need 64bit on windows. Even if we want to increase the map size one day, the difference between 8 and 32 bit will probably be a big enough jump.

**Comment by turican0** [comment]
It's not just the size of the maps. But 64bit is the de facto standard today. For me, the game runs almost 2x faster in 64-bit. And also 32bit support in windows probably won't be around forever.

**Comment by turican0** [comment]
By the way, the original game was 32-bit, not 8-bit. Only the bootloader was 16-bit, but that was only used to load the code.

**Comment by thobbsinteractive** [comment]
I thought it ran in DOS so would be 16bit at most? i.e. the normal Int in Borland C/C++ was 16bit. Anyway. You said to fix this we need to change fopen?

**Comment by turican0** [comment]
It's WATCOM C++ programming:
https://tuttlem.github.io/2015/10/04/32bit-dos-development-with-open-watcom.html

**Comment by turican0** [comment]
Try switching your build to x64 and you'll see. It writes a couple of errors on the override (char*) and then the fopen( error.

**Comment by thobbsinteractive** [comment]
Sure will do. I will try adding it to the Actions too

**Comment by turican0** [comment]
Ok, thanks, it's better if it's checked automatically.

**Comment by thobbsinteractive** [comment]
It builds! And yes @turican0, it is a lot faster now rendering (by about 20-30%). My guess is that is might be something to do with using the full bus for Maths operations? But it is now almost playable in Full HD.

**Comment by turican0** [comment]
There are also more registers in x64, so this may reduce the need to read/write to memory.
