### ISSUE TITLE
Flight assist is responding incorrectly

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#134]

**Comment by thobbsinteractive** [comment]
The manual mentions nothing about what Flight Assistance does. I am guessing it rolls the player back to level if they stop turning?

**Comment by thobbsinteractive** [comment]
The manual mentions nothing about what Flight Assistance does. I am guessing it rolls the player back to level if they stop turning?

**Comment by turican0** [comment]
Sure, but it's falling over to one side for me, but I haven't had time to research whether it depends on the resolution. I'll look into it in the next wave.

**Comment by turican0** [comment]
In this ok
![image](https://user-images.githubusercontent.com/41465132/185215934-2f2897cc-881b-42e8-8623-edda31609866.png)

**Comment by turican0** [comment]
Problem is only in resolution  bigger 640.

**Comment by turican0** [comment]
Problem may be in void SetMousePosition_6EDE0(int16_t posX, int16_t posY)//24fde0

**Comment by turican0** [comment]
I test this variables:
&unk_18058Cstr.x_DWORD_1805B0_mouse.x
&x_WORD_E3760_mouse.x
D41A0_0.array_0x2BDE[a1x->dword_0xA4_164x->word_0x38_56].dword_0x3E6_2BE4_12228.position_backup_20.x

**Comment by turican0** [comment]
screenWidth_18062C is incorrect in SetMousePosition_6EDE0

**Comment by turican0** [comment]
I test change to gameResWidth

**Comment by turican0** [comment]
Fixed:
void SetMousePositionByRes_6EDB0()//24FDB0 //fly asistant
{
	if (x_WORD_180660_VGA_type_resolution == 1)
		SetMousePosition_6EDE0(320, 200);
	else
	{
		if (!DefaultResolutions())
			SetMousePosition_6EDE0(320, 200); !!!!!!!!!!!
		else
			SetMousePosition_6EDE0(320, 240);
	}
}

**Comment by thobbsinteractive** [comment]
Fixed!
