### ISSUE TITLE
Hidden level not visible on level map

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#139]
GrimSqueaker — 14.8.22 22:15
it was this level. according to https://www.uhs-hints.com/uhsweb/hints/mcarpet2/233.php it is called gleph. i have a savegame right at the end of the level where the game wants me to go to the hidden level portal but it is not there. i'll try to upload the savegame.
![image](https://user-images.githubusercontent.com/41465132/184581843-538df1e3-f48f-49b3-a7f3-7060716d63c3.png)
the one, that the carpet is hovering on
let me read up on your conversation a bit.

**Comment by turican0** [comment]
In DOSBOX is same - problem not in drawing, but in create/modify data secretMapScreenPortals_E2970.
![image](https://user-images.githubusercontent.com/41465132/185742768-151c6ee3-ae6a-4eef-a2e3-e199a9192f92.png)

**Comment by turican0** [comment]
![image](https://user-images.githubusercontent.com/41465132/185743288-1a906057-7610-4488-ac30-73d8b5d750ac.png)
I think that's fine, some portals are just not visible in the game. It's also not visible in Dosbox. And the longplay on youtube isn't either:
https://www.youtube.com/watch?v=3R_LfhpOidw&list=PLA5DA424CE767D0C7&index=22

**Comment by turican0** [comment]
And if you mean the portal that the player slides into automatically, I've seen that in all versions:
![image](https://user-images.githubusercontent.com/41465132/185744322-8f9a5510-47a7-41ef-be37-dddd91fe0324.png)

**Comment by turican0** [comment]
![image](https://user-images.githubusercontent.com/41465132/185744366-c0f448b8-507a-4fc8-aa93-1acb4bda886f.png)
And if you mean the marker on the map, that also shows up everywhere.

**Comment by thobbsinteractive** [comment]
Okay. So the Portal appears for me (after destroying the castle that appears). The load of the hidden level crashed in the Sprites code. Unfortunately I didn't skip over this error correctly. But the portal did appear and the level started loading.

**Comment by turican0** [comment]
I guess I'm dumb, but I still don't know what specifically isn't working :) Can't you describe it more precisely? If the icon in the map disappears, or the portal in the game? I didn't discover anything strange, either it's just bothering someone or I don't know what to look for. Unless it's a major bug, I'll focus on it after the code is completely cleaned up, but that's a long time away.

**Comment by thobbsinteractive** [comment]
I think we can close it. The portal opens, the icon there. The hidden level
starts loading (but crashed due to Sprite code in my case). It maybe that
it crashes every time, but we would raise that as another bug.

**Comment by turican0** [comment]
Ok, if it was at a higher resolution than 640x480 it's ok because those are known issues with the renderer.
So I'll close this bug.
