### ISSUE TITLE
Add upscale sky to upscaled graphics

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#140]

**Comment by thobbsinteractive** [comment]
This would be nice.

**Comment by turican0** [comment]
I finish it.

**Comment by thobbsinteractive** [comment]
I will reopen this just because until it is merged it is not "technically" fixed and I am still working on the PR

**Comment by turican0** [comment]
Ok, it's better to close bugs after folding into the main branch.
