### ISSUE TITLE
Better HD textures

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#150]
Use smarter algoritmus for translate HD textures.

**Comment by thobbsinteractive** [comment]
You know, I am pretty happy with the current quality Sprites. The textures could definitely use some work.

**Comment by turican0** [comment]
I'm starting with sprites, but I mean textures as well.

**Comment by turican0** [comment]
Remove colors 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7 from night sprites.

**Comment by thobbsinteractive** [comment]
So the night sprites are still not blending incorrectly for the HD Textures. The building Windows should show entirely, The gold mana balls should fade e.g:
![image](https://user-images.githubusercontent.com/19335188/195172885-b0c3665f-f222-4b63-bcb0-6f5318d5708d.png)
The original textures work, so this seems to be an issue with the up-scaling probably where it is blending colours together?

**Comment by turican0** [comment]
I don't want to risk the colors being wrong for some textures, so I'd rather go back to using only the colors that were in the smaller textures for now - just for the night levels for now. I've already adjusted the tools, but I'll generate the textures on Monday. When I explore the renderer more over time I can fix it better, but that won't be for a few months.

**Comment by thobbsinteractive** [comment]
Fixed!
