### ISSUE TITLE
Interesting informations (about glitches)

### ISSUE THREAD

**Issue by turican0** [thobbsinteractive/magic-carpet-2-hd#155]
https://kb.speeddemosarchive.com/Magic_Carpet_2/Game_Mechanics_and_Glitches

**Comment by thobbsinteractive** [comment]
Very cool

**Comment by turican0** [comment]
Besides, even the original game sometimes crashes in high resolution, so it's a bug in the engine design.

**Comment by turican0** [comment]
I move this to WIKI
