### ISSUE TITLE
In current dev, FX sound volume change is not saved.

### ISSUE THREAD

**Issue by thobbsinteractive** [thobbsinteractive/magic-carpet-2-hd#169]
Start the first level, pause, change the FX volume to 1/2. Resume the same. The FX level has not changed.

This should change the Sound FX levels throughout the game. Effecting the menu sounds as well (but not the music or into/cut-scenes)

**Comment by turican0** [comment]
Hi, I've created another PR to fix the sound, so hopefully it will be ok now, I haven't found any problem with mine. Please merge it.

**Comment by thobbsinteractive** [comment]
Fixed!
