### ISSUE TITLE
Suggestion to improve compilation instructions on linux

### ISSUE THREAD

**Issue by VenKamikaze** [thobbsinteractive/magic-carpet-2-hd#183]
Hi,

Compilation is much improved from a few months ago! Thanks.

One minor suggestion though is to include that you need to initialise the git submodules so that 'findfirst' can be compiled, e.g:
`git submodule init && git submodule update`

It'd be good to include that in your compilation instructions just before doing:
`cd build/${BUILDTYPE}`
`cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DCMAKE_INSTALL_PREFIX=./inst [SOURCE_DIR]`

Cheers

**Comment by VenKamikaze** [comment]
If you didn't need it when testing on the Pi, then you probably did a recursive clone when cloning the repository (or the tool you used did it for you). That has the same effect as a doing the submodule init and update.

Even if you don't include the git submodule init && git submodule update - just mentioning in the instructions somewhere that you either need to initialise submodules or recursively clone when pulling down the repository would help.

**Comment by thobbsinteractive** [comment]
Hi @VenKamikaze. I don't mind at all adding that line. We can do this one of two ways:
- You can create a branch, modify the instructions and then create a pull request.
- Or you can tell me what and where exactly to put it in the instructions and I can do the pull request etc...

**Comment by VenKamikaze** [comment]
No worries. I will do one at some point :)

**Comment by thobbsinteractive** [comment]
Added suggested comments to readme
