### ISSUE TITLE
Level 20 crashes after a minute or so of play when accessing illegal memory in the str_D93C0_bldgprmbuffer

### ISSUE THREAD

**Issue by thobbsinteractive** [thobbsinteractive/magic-carpet-2-hd#188]
Unhandled exception at 0x7592CA42 in remc2.exe: Microsoft C++ exception: std::out_of_range at memory location 0x00BEED38.

Changing the size of this vector from 76 to 78 seems to fix this issue

**Comment by thobbsinteractive** [comment]
Yep. I can play the whole level though

**Comment by thobbsinteractive** [comment]
Wow. Those zeros, are they some kind of end marker? Like \0 is for a cstr?

**Comment by turican0** [comment]
Basically, yes, you can notice this with multiple structures. The loop loads rows until it gets to zero.

**Comment by turican0** [comment]
In our case it is checked by byte_2:
while (!(str_D93C0_bldgprmbuffer.at(v2).byte_2 & 2) && v1 < 0x4Du)

**Comment by turican0** [comment]
Previously, we were probably lucky that this structure was followed by zeros in memory, so it didn't crash.

**Comment by thobbsinteractive** [comment]
fixed!
