### ISSUE TITLE
GOG Offline/backup installed copy of the game cannot be extracted by MSI

### ISSUE THREAD

**Issue by thobbsinteractive** [thobbsinteractive/magic-carpet-2-hd#252]

**Comment by thobbsinteractive** [comment]
Hi. I have found it is a permission issue. It will be fixed in the next
Release.

**Comment by thobbsinteractive** [comment]
The game in the next release can now be installed using the just the CD. It will not bring across the save files in this case though. When it is run it will run the built in code to basically install the game. I think this will work well for most people. I have a few more days work on the MSI until I can release it. I need to check the upgrading code works and I would like it to rip the tracks from the CD.

**Comment by cyberpunk2021** [comment]
The new version installer works fine, thanks a lot !

**Comment by thobbsinteractive** [comment]
Thanks for testing!
