### ISSUE TITLE
Relation with remc2?

### ISSUE THREAD

**Issue by cxong** [thobbsinteractive/magic-carpet-2-hd#269]
How is this project related to remc2? Is this a continuation, has remc2 been abandoned?

https://github.com/opengaming/osgameclones/issues/2424

**Comment by thobbs-mifcom** [comment]
I believe the original remc2 is abandoned, Tomas (who owns the repo) is now remaking Magic Carpet in a new engine. I am working on a Magic Carpet 1 Editor at the moment, but will be back with this project in a month. It has just taken 10 times longer than I planned (I was trying to use a new framework and design pattern (MVVM) so the learning curve was steep)
Before working on the Editor, I was working on merging in an OpenAL pull request. I wanted to let the user selected between the existing SDL sound the new OpenAL in the config. So it will continue, just in a week or two
