### ISSUE TITLE
 The reflection geometry is sometimes draw all the way into the sky (In resolutions at or higher than 1024).

### ISSUE THREAD

**Issue by Tim-Hobbs** [thobbsinteractive/magic-carpet-2-hd#40]
This is most likely a memory leak and has been occurring since I got higher resolutions working

**Comment by thobbsinteractive** [comment]
When paused this seems to be animated, possible the water texture

**Comment by thobbsinteractive** [comment]
![image](https://user-images.githubusercontent.com/19335188/116788441-dd10e900-aaa9-11eb-893e-f75af33a6b7f.png)

**Comment by thobbsinteractive** [comment]
It is also sometimes the building textures. It is clearly a leak either way

**Comment by Tim-Hobbs** [comment]
So I don't think this is a leak. It is more likely that above 640x480 the vertexs for the terrain are miss calculated. 
It might be worth testing with reflections turned off to see if the problem occurs as it is animated as if below water.

**Comment by thobbsinteractive** [comment]
This problem stops if the reflections are turned off

**Comment by thobbsinteractive** [comment]
So I have checked the contents of the projectedVertexBuffer passed into the SubDrawInverseTerrainAndParticles with lower resolutions 320x200 and HD resolution, they are the same.
So the miss-calculation is happening in SubDrawInverseTerrainAndParticles()

**Comment by thobbsinteractive** [comment]
In further testing it, seems this problem only happens when the player height is around Z = 2300 and above in HD resolution.

**Comment by thobbsinteractive** [comment]
So the problem happens sporadically at Z = 2250 as the player turns at HD resolution. So this is likely a distance calculation possibly to do with the size of the view port.

**Comment by thobbsinteractive** [comment]
At 2k the problem starts at Z = 3850.

**Comment by thobbsinteractive** [comment]
So it might be a problem with the coordinates calculated.
Screen coordinates are:
`0,0 ------------- 1920`
` |`
` |`
` |`
`1080`
And yet something is generating reflection coordinates that filling the screen

**Comment by thobbsinteractive** [comment]
So this is interesting. I have logged and compared the polys being drawn in 1920x1080 when the problem occurs and after switching to 320x200 (with the R key) when it does not (see attached).
When you look at the X and Y values as a percentage of screen size they seem to be about the same.

But about 2/3 though the frame, I can see errors in the values at [14:51:10:916713 +02:00] and [14:43:23:379480 +02:00]:

![image](https://github.com/user-attachments/assets/5c6e38d8-5bd9-46f9-ae5b-001bad52966d)

[log-highres.txt](https://github.com/user-attachments/files/16569699/log-highres.txt)
[log-lowres.txt](https://github.com/user-attachments/files/16569700/log-lowres.txt)

**Comment by thobbsinteractive** [comment]
So these values are populated by  `Str_E9C38_smalltit[v151x - 1].pnt3_24` in `SubDrawInverseTerrainAndParticles`

Within the above method `DrawTerrainAndParticles_3C080` `Str_E9C38_smalltit[v151x - 1].pnt3_24` is populated by `projectedVertexBuffer[25]` and this is in turn populated by `((str_F2C20ar.cos_0x11 * Str_E9C38_smalltit[v124x].pnt1_16 - str_F2C20ar.sin_0x0d * Str_E9C38_smalltit[v124x].pnt4_28) >> 16) + str_F2C20ar.dword0x24;`

**Comment by thobbsinteractive** [comment]
So I have found one issue here, that was likely causing occasional issues but is not the root cause. When multiplying by SIN at higher resolutions it was occasionally creating values above 2.1 billion before bit shifting them. In lines like this one:
`((str_F2C20ar.cos_0x11 * Str_E9C38_smalltit[v124x].pnt1_16 - str_F2C20ar.sin_0x0d * Str_E9C38_smalltit[v124x].pnt4_28) >> 16) + str_F2C20ar.dword0x24;`

 I will put in a fix for that by casting.

But I finally think I have found the cause after weeks of looking. It is still just a theory, but the problem does not happen in the Cave levels or to the other fix geometry, only the reflection which has a Wave effect applied to it. I think this is the cause! 
So I just need to find where this effect is applied to vertexes. This should be something like `(sin * time) + position` but I have not found it yet.

**Comment by thobbsinteractive** [comment]
So, it is not the Wave. I found the code that performed the waving of the vertexes. set it to a fixed value and the issue still happens.

**Comment by thobbsinteractive** [comment]
Worse, this extreme geometry seems to be causing a memory leak and crash.

**Comment by thobbsinteractive** [comment]
I was worried that maybe I had found some unreliable data. But with the game paused and the wave fixed I got the following:
![image](https://github.com/user-attachments/assets/3e00454a-e4b4-49fe-906c-b176392e2300)
[320-vertexes-78-75.txt](https://github.com/user-attachments/files/16826056/320-vertexes-78-75.txt)
[1920-vertexes-78-75.txt](https://github.com/user-attachments/files/16826057/1920-vertexes-78-75.txt)

I have studied the generation of these values, proportionally (scaled up from 320x200) everything looks fine. I cannot find what is causing these inverse values.

**Comment by thobbsinteractive** [comment]
So the issue was that when calculating rotation and translation it was overrunning the 2.1 billion of int. I thought I had fixed this by casting to long, but in C++ they are the same length. I used int64_t and it seems to have fixed the issue for HD and 2k
