### ISSUE TITLE
Level 9 crashes at start with blank "placeholder" in required data array.

### ISSUE THREAD

**Issue by Tim-Hobbs** [thobbsinteractive/magic-carpet-2-hd#41]
Fly around the pond at the start of the level and this crash will occur. I believe an item has not been loaded.

**Comment by thobbsinteractive** [comment]
This turned out to be an indexing error introduced sub_71E70 (now called LoadTMapMetadata_71E70) to was causing bogus tmap data to be loaded sometimes.
