### ISSUE TITLE
Linux automated build (action) is failing

### ISSUE THREAD

**Issue by Tim-Hobbs** [thobbsinteractive/magic-carpet-2-hd#61]
This is due (at the moment) to a broken repo link.

**Comment by thobbsinteractive** [comment]
[GrimSqueaker](https://github.com/GrimSqueaker) commented [20 hours ago](https://github.com/thobbsinteractive/magic-carpet-2-hd/pull/67#issue-1272615278)
Fixed the Linux 64 bit build, but had to ditch the 32 bit build on Github as installing the required dependencies does not work in the Github runner.
It makes sense to focus only on getting the 64 bit build working. The current state of 64 bit on Linux: Intro, Menu, Level-Selection, and Loading seem to work. The game crashes with a segfault after a few frames when starting a level.
