### ISSUE TITLE
Sky loses detail when using multi-threaded rendering

### ISSUE THREAD

**Issue by GrimSqueaker** [thobbsinteractive/magic-carpet-2-hd#88]
Single thread:
![Screenshot from 2022-06-27 20-18-44](https://user-images.githubusercontent.com/26384847/176009473-610387a5-aaa0-4c98-b5a9-9b6bf99e0120.png)

7 threads:
![Screenshot from 2022-06-27 20-19-01](https://user-images.githubusercontent.com/26384847/176009518-2b1b66e5-7c19-4713-a389-305c7ea2313d.png)

**Comment by thobbsinteractive** [comment]
Yeah I noticed that. I am still not sure why it happens. Thanks for logging it. 
The code just skips a line/lines. It could be the maths involved requires some data from the previous lines. I will look into it
