### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by GrimSqueaker** [thobbsinteractive/magic-carpet-2-hd#99]
Last year I did set up a first UT with the intention to check if the structures that need to stay unmodified are always checked. I did not make this part of a build yet. The structure that is checked seems anyhow to not have its original size anymore.

However, if you have code or structures that you want to unit test it would be great if you could write some test code as the framework is already available.
Then I could also add these checks to the Linux build.

Take a look at `remc2/UnitTests.cpp` for an example.

**Comment by thobbsinteractive** [comment]
So I will take a look at moving the Unit Test into their own folder and project in visual studio (perhaps there is also a test runner we can use there). We can then hopefully add them to the build actions.
Once this works, ideally for every bug fix we need to:
- Refactor the code involved to use local variables as much as possible.
- Write a UT that runs the fixed methods with at least a mock scenario that reproduces the bug.
I realize this makes bug fixes take a lot longer and heck I hate doing it too, but for regression testing it is invaluable.

**Comment by thobbsinteractive** [comment]
This is now done and running UTs in all builds
